### ISSUE TITLE
Feature Request: (self) and (@self) to insert bots own name

### ISSUE THREAD

**Issue by ghost** [ArkaneMoose/BotBot#40]
totallyhuman was looking for this feature and I think it would be easy to add similar to (sender) I found the place in botparser.py where this is done but I was having trouble knowing what to replicate.... it would just be a case of passing self.nickname to the parser and duplicating existing code but changing these three lines:

search_string = content.replace(EuphUtils.mention(sender), '(@sender)')
search_string = content.replace(sender, '(sender)')
search_string = content.replace(EuphUtils.mention(sender), '(@sender)').replace(sender, '(sender)')

to use the value sent to the parser from the botbotbots self.nickname (or the bot.nickname if it's sent from a botbotbot collection not the bot itself)

this was just a bit too complex for me without having access to a test environment.

-Etchy (now called Kaze Brightside on euphoria, my github changed too)

**Comment by totallyhuman** [comment]
o/

EDIT: I know, I know, useful comments, bla bla bla.

**Comment by ArkaneMoose** [comment]
I've implemented the (self) and (@self) variables in responses in c9bde0d, but your description seems to imply that you want to match (self) and (@self) in the regex.

The `search_string = content.replace(...)` thing is really very hacky. We need a better way to do variables in regexes.

If c9bde0d does all you want it to, feel free to close this issue. Otherwise, I'm leaving it open until I can figure out a better way to match variables in regexes.

**Comment by totallyhuman** [comment]
That was what I was looking for originally, yeah. However, having it in the regex might be a cool addition.

**Comment by ArkaneMoose** [comment]
With the [new-style variable syntax](https://github.com/ArkaneMoose/BotBot/wiki/Variables-and-math#variables), you can use `${self}` and `${atself}` to match the bot's name and its @-mention respectively. For that reason, I will be closing this almost year-old issue. Feel free to create a new issue if there's something else you want added.
