### ISSUE TITLE
Bot responds to '!help' indiscriminately

### ISSUE THREAD

**Issue by iykdw** [ArkaneMoose/BotBot#43]
# Issue:
@BotBot responds to `!help randomstring @Anotherbotname` or `!help randomstring`

## Expected behaviour:
`!help @BotBot` -> long help message
`!help` -> short help message
`!help randomstring @AnotherBot` -> no help message
`!help randomstring` -> no help message

## Actual behaviour
`!help @BotBot` -> long help message
`!help` -> short help message
`!help randomstring @AnotherBot` -> short help message
`!help randomstring` -> short help message

## Steps to reproduce
1. In a room where @BotBot is present, send the message `!help randomstring` or `!help randomstring @anotherbot`
2. Observe @BotBot reply

# Proposed fix
Require `!help` to be only contents of message for @BotBot to give short help message. I'll make the fix in my fork and lodge a PR.

**Comment by iykdw** [comment]
Regarding my proposed fix; I don't understand the philosophy behind handling bang commands the way you do, so I'll hang fire on a PR (my fix would more or less be "if command.strip() == 'help':")

**Comment by ArkaneMoose** [comment]
It's not a bug, it's a feature! Or it was supposed to be, anyway.

It was intended to allow users to leave comments on commands. I use this myself sometimes, when I type things like `!restart @BotBot because of some reason`.

When you type `!help randomstring @Anotherbot`, BotBot sees that as `!help (ignored comment)`.

I do see why this might be an issue, though. I can think of three potential ways of solving them.

- Disallow comments entirely.
  - `!help @BotBot something` would have no effect.
- Allow comments only on commands specifically intended for BotBot.
  - `!help something` would have no effect.
  - `!help @BotBot something` would have the same effect as `!help @BotBot`.
- Search the string for an @-mention, and if it contains one that is not `@BotBot`, ignore it.
  - `!help something` would have the same effect as `!help`.
  - `!help something @AnotherBot` would have no effect.
  - `!help @BotBot something` would have the same effect as `!help @BotBot`.
  - (Optional) `!help something @BotBot` would have the same effect as `!help @BotBot`.

Let me know which solution you think is best, or if there is a different solution you'd prefer.

**Comment by ArkaneMoose** [comment]
Personally, I think the second solution is best because it is simple to implement while still being close to the intended functionality.

**Comment by iykdw** [comment]
You sound just like my boss when I file bug reports...

Ahem. I'm in agreement that number two is good - I think it remains close to the original and gives botling-creators freedom to implement arguments and flags, which is what brought this to my attention originally. And it does seem almost trivial to implement.
`match = EuphUtils.command('help', self.nickname).match(command)`, right?

**Comment by ArkaneMoose** [comment]
The change would need to be made in `euphutils.py`, in the `command()` method, which does the command parsing. I'll do that now.

**Comment by iykdw** [comment]
Ah, thank you. Yes, I completely misread the code there. Idiot :-P
